[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "milap"
version = "0.1.0"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
    "src",
    "src/milap",
    "mila",
]
